= DataFlow showcase application

== Prerequisites

.Clone the project
[source,bash]
----
cd ..
git clone https://github.com/austek/dataflow-pipeline

----

.Starting Pulsar standalone
[source,bash]
----
docker run --name pulsar-standalone -d -p 8080:8080 -p 6650:6650 apachepulsar/pulsar:latest /pulsar/bin/pulsar standalone
----

== Usage

.Run the application
[source,bash]
----
./gradlew :bootRun
----

.Run the webhook application
[source,bash]
----
./gradlew :webhook-target-app:bootRun
----

== Sensor ingest demonstration

NOTE: This requires gnu `shuf` (on MacOS: `brew install coreutils`, use `gshuf` instead of `shuf`).

=== Sending 1M sensor entries with curl, all in one request

[source,bash]
----
for i in {1..1000000}; do
  echo '{"name": "Sensor-'$i'", "value": '$(shuf -i 20-49 -n 1)'}' \
    | curl -X POST -T - -H "Content-Type: application/x-ndjson" localhost:8081/sensors
done
----

=== Sending 1M sensor entries with curl, 1 message per request, with up to 50 parallel requests

NOTE: This requires gnu `xargs` (on MacOS: `brew install findutils`, use `gxargs` instead of `xargs`)
and gnu parallel (`brew install parallel`/`apt install moreutils`).

[source,bash]
----
{ for i in {1..1000000}; do
  echo -ne 'curl -s -X POST -d '\''{"name": "Sensor-'$i'", "value": '$(shuf -i 20-49 -n 1)'}\'' -H "Content-Type: application/x-ndjson" localhost:8081/sensors''\0'; done; } \
  | xargs -0 -P 2 -n 100 parallel -j 25 --
----

=== Sending 10000 sensor entries with curl, 1 message per request (slow!)

[source,bash]
----
for i in {1..10000}; do
  echo '{"name": "Sensor-'$i'", "value": '$(shuf -i 20-49 -n 1)'}' \
    | curl -X POST -T - -H "Content-Type: application/x-ndjson" localhost:8081/sensors
done
----

=== Sending 1M sensor entries (1000 devices, 1000 metrics) with curl, all in one request

[source,bash]
----
{ for i in {1..1000}; do for j in {1..1000}; do
  echo '{"name": "Sensor-'$i'", "value": '$(shuf -i 20-49 -n 1)'}'; done; done; } \
    | curl -X POST -T - -H "Content-Type: application/x-ndjson" localhost:8081/sensors
----

=== Sending 1M sensor entries with k6

Requires https://k6.io/docs/getting-started/installation/[installing k6].

[source,bash]
----
cd k6
k6 run -u 100 -i 1000000 sensors_ingest.js
----
Z