server:
  port: 8081
spring:
  pulsar:
    client:
      service-url: pulsar://localhost:6650
#    defaults:
#      type-mappings:
#        - message-type: com.collibra.events.model.SensorEvent
#          topic-name: sensors_ingest
#          schema-info:
#            schema-type: JSON

logging.level:
  org.apache.pulsar: info
